name = "company_public_comps"
version = "v1"

description = "Extract public comparable companies and relevant trading metrics"

enabled = true
model_complexity = "medium"

[[fields]]
id = "company_name"
type = "string"
required = true
description = "The name of the private company being evaluated"

# ----------------------------------------------------------------------------

[[fields]]
id = "public_comps"
type = "text"
required = false
description = "A comma-separated list of public comparable companies used for valuation benchmarking"
