name = "company_customer_quotes"
version = "v1"

description = "Extract direct quotes and testimonials from customers"

enabled = true
model_complexity = "hard"

[[fields]]
id = "company_name"
type = "string"
required = true
description = "The name of the company receiving the testimonials"

# ----------------------------------------------------------------------------

[[fields]]
id = "customer_quotes"
type = "text"
required = false
description = "A summary or list of notable customer quotes praising the product or service"
