"""Add address and type columns

Revision ID: 063b594c7675
Revises: 8b190512ed2b
Create Date: 2026-05-30 10:20:47.652277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063b594c7675'
down_revision: Union[str, Sequence[str], None] = '8b190512ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_profiles', sa.Column('investment_fund_type', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('street1', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('street2', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('state', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('street1', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('street2', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'zip_code')
    op.drop_column('organizations', 'street2')
    op.drop_column('organizations', 'street1')
    op.drop_column('fund_profiles', 'zip_code')
    op.drop_column('fund_profiles', 'country')
    op.drop_column('fund_profiles', 'state')
    op.drop_column('fund_profiles', 'city')
    op.drop_column('fund_profiles', 'street2')
    op.drop_column('fund_profiles', 'street1')
    op.drop_column('fund_profiles', 'investment_fund_type')
    # ### end Alembic commands ###
