"""Add Security and DataPullRun models

Revision ID: 068686fe7767
Revises: d6b7d8e93e53
Create Date: 2026-08-30 20:39:16.374426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '068686fe7767'
down_revision: Union[str, Sequence[str], None] = 'd6b7d8e93e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_pull_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_pull_runs_id'), 'data_pull_runs', ['id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('security_type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_id'), 'securities', ['id'], unique=False)
    op.create_index(op.f('ix_securities_ticker'), 'securities', ['ticker'], unique=False)
    op.drop_index(op.f('ix_comparison_set_company_links_id'), table_name='comparison_set_company_links')
    op.drop_table('comparison_set_company_links')
    op.create_unique_constraint('uq_market_comparison_set', 'market_comparison_set_links', ['market_id', 'comparison_set_id'])
    op.drop_column('markets', 'sector')
    op.add_column('metric_observations', sa.Column('security_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'metric_observations', 'securities', ['security_id'], ['id'])
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'metric_observations', type_='foreignkey')
    op.drop_column('metric_observations', 'security_id')
    op.add_column('markets', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_market_comparison_set', 'market_comparison_set_links', type_='unique')
    op.create_table('comparison_set_company_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comparison_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], name=op.f('comparison_set_company_links_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_sets.id'], name=op.f('comparison_set_company_links_comparison_set_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comparison_set_company_links_pkey'))
    )
    op.create_index(op.f('ix_comparison_set_company_links_id'), 'comparison_set_company_links', ['id'], unique=False)
    op.drop_index(op.f('ix_securities_ticker'), table_name='securities')
    op.drop_index(op.f('ix_securities_id'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_data_pull_runs_id'), table_name='data_pull_runs')
    op.drop_table('data_pull_runs')
    # ### end Alembic commands ###
