"""Add announced_date to FinancingRound

Revision ID: 1730d59d4a00
Revises: 068686fe7767
Create Date: 2026-09-13 16:06:48.646348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1730d59d4a00'
down_revision: Union[str, Sequence[str], None] = '068686fe7767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financing_rounds', sa.Column('announced_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financing_rounds', 'announced_date')
    # ### end Alembic commands ###
