"""Add source_type to SourceDocument

Revision ID: 280cc7b01445
Revises: 36b1b2722eeb
Create Date: 2026-07-01 21:36:19.850613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280cc7b01445'
down_revision: Union[str, Sequence[str], None] = '36b1b2722eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('source_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'source_type')
    # ### end Alembic commands ###
