"""Add investment explicit amounts and source link

Revision ID: 36b1b2722eeb
Revises: 41671816de05
Create Date: 2026-07-01 21:05:19.678066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b1b2722eeb'
down_revision: Union[str, Sequence[str], None] = '41671816de05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('total_round_amount', sa.String(), nullable=True))
    op.add_column('investments', sa.Column('firm_investment_amount', sa.String(), nullable=True))
    op.add_column('investments', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'investments', 'source_documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_column('investments', 'source_document_id')
    op.drop_column('investments', 'firm_investment_amount')
    op.drop_column('investments', 'total_round_amount')
    # ### end Alembic commands ###
