"""Add CompanyAugmentationReport and SourceDocument columns

Revision ID: 41671816de05
Revises: c9c3c6da4c8c
Create Date: 2026-06-11 22:07:19.348850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41671816de05'
down_revision: Union[str, Sequence[str], None] = 'c9c3c6da4c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_augmentation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('extracted_data_json', sa.JSON(), nullable=True),
    sa.Column('scoring_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_augmentation_reports_id'), 'company_augmentation_reports', ['id'], unique=False)
    op.add_column('source_documents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('source_documents', sa.Column('source_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'source_name')
    op.drop_column('source_documents', 'title')
    op.drop_index(op.f('ix_company_augmentation_reports_id'), table_name='company_augmentation_reports')
    op.drop_table('company_augmentation_reports')
    # ### end Alembic commands ###
