"""Make organization_type required

Revision ID: 42114f2b3da8
Revises: d4f3f38c4a0b
Create Date: 2026-08-04 09:30:52.690200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42114f2b3da8'
down_revision: Union[str, Sequence[str], None] = 'd4f3f38c4a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'organization_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'organization_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
