"""Init

Revision ID: 4828553752d6
Revises: 
Create Date: 2026-05-23 10:06:26.976297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4828553752d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('primary_domain', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_normalized_name'), 'organizations', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_organizations_primary_domain'), 'organizations', ['primary_domain'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('subindustry', sa.String(), nullable=True),
    sa.Column('company_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    op.create_table('fund_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_organization_id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_type', sa.String(), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('fund_size', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_profiles_id'), 'fund_profiles', ['id'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('investor_type', sa.String(), nullable=True),
    sa.Column('preferred_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_investor_profiles_id'), 'investor_profiles', ['id'], unique=False)
    op.create_table('person_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_type', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_person_emails_id'), 'person_emails', ['id'], unique=False)
    op.create_table('person_organization_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('seniority_level', sa.String(), nullable=True),
    sa.Column('role_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_primary_role', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_organization_roles_id'), 'person_organization_roles', ['id'], unique=False)
    op.create_table('program_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_organization_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('program_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_profiles_id'), 'program_profiles', ['id'], unique=False)
    op.create_table('program_cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_cohorts_id'), 'program_cohorts', ['id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('program_cohort_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_profiles.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['program_cohort_id'], ['program_cohorts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_table('program_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_organization_id', sa.Integer(), nullable=False),
    sa.Column('program_cohort_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['program_cohort_id'], ['program_cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_memberships_id'), 'program_memberships', ['id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('source_identifier', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=False)
    op.create_table('document_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_texts_content_hash'), 'document_texts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_texts_id'), 'document_texts', ['id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('document_text_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('llm_usage_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_text_id'], ['document_texts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_id'), 'extraction_jobs', ['id'], unique=False)
    op.create_table('canonical_mutations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_entity_type', sa.String(), nullable=False),
    sa.Column('canonical_entity_id', sa.String(), nullable=False),
    sa.Column('mutation_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extraction_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_mutations_canonical_entity_id'), 'canonical_mutations', ['canonical_entity_id'], unique=False)
    op.create_index(op.f('ix_canonical_mutations_id'), 'canonical_mutations', ['id'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_job_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('extracted_payload_json', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_id'), 'extracted_entities', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_normalized_name'), 'extracted_entities', ['normalized_name'], unique=False)
    op.create_table('entity_attribute_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_entity_type', sa.String(), nullable=False),
    sa.Column('canonical_entity_id', sa.String(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('attribute_value_json', sa.JSON(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_entity_id'], ['extracted_entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_attribute_evidences_canonical_entity_id'), 'entity_attribute_evidences', ['canonical_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_attribute_evidences_id'), 'entity_attribute_evidences', ['id'], unique=False)
    op.create_table('entity_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_entity_id', sa.Integer(), nullable=False),
    sa.Column('canonical_entity_type', sa.String(), nullable=False),
    sa.Column('canonical_entity_id', sa.String(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_entity_id'], ['extracted_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_matches_canonical_entity_id'), 'entity_matches', ['canonical_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_matches_id'), 'entity_matches', ['id'], unique=False)
    op.create_table('extracted_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_job_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('source_extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('source_entity_type', sa.String(), nullable=True),
    sa.Column('source_entity_id', sa.String(), nullable=True),
    sa.Column('target_extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_type', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('relationship_payload_json', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_extracted_entity_id'], ['extracted_entities.id'], ),
    sa.ForeignKeyConstraint(['target_extracted_entity_id'], ['extracted_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_relationships_id'), 'extracted_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_relationships_id'), table_name='extracted_relationships')
    op.drop_table('extracted_relationships')
    op.drop_index(op.f('ix_entity_matches_id'), table_name='entity_matches')
    op.drop_index(op.f('ix_entity_matches_canonical_entity_id'), table_name='entity_matches')
    op.drop_table('entity_matches')
    op.drop_index(op.f('ix_entity_attribute_evidences_id'), table_name='entity_attribute_evidences')
    op.drop_index(op.f('ix_entity_attribute_evidences_canonical_entity_id'), table_name='entity_attribute_evidences')
    op.drop_table('entity_attribute_evidences')
    op.drop_index(op.f('ix_extracted_entities_normalized_name'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_canonical_mutations_id'), table_name='canonical_mutations')
    op.drop_index(op.f('ix_canonical_mutations_canonical_entity_id'), table_name='canonical_mutations')
    op.drop_table('canonical_mutations')
    op.drop_index(op.f('ix_extraction_jobs_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_document_texts_id'), table_name='document_texts')
    op.drop_index(op.f('ix_document_texts_content_hash'), table_name='document_texts')
    op.drop_table('document_texts')
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_program_memberships_id'), table_name='program_memberships')
    op.drop_table('program_memberships')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_program_cohorts_id'), table_name='program_cohorts')
    op.drop_table('program_cohorts')
    op.drop_index(op.f('ix_program_profiles_id'), table_name='program_profiles')
    op.drop_table('program_profiles')
    op.drop_index(op.f('ix_person_organization_roles_id'), table_name='person_organization_roles')
    op.drop_table('person_organization_roles')
    op.drop_index(op.f('ix_person_emails_id'), table_name='person_emails')
    op.drop_table('person_emails')
    op.drop_index(op.f('ix_investor_profiles_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    op.drop_index(op.f('ix_fund_profiles_id'), table_name='fund_profiles')
    op.drop_table('fund_profiles')
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_table('people')
    op.drop_index(op.f('ix_organizations_primary_domain'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_normalized_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
