"""Add CRM metrics and financing rounds

Revision ID: 64ea6a95a1b7
Revises: 7b452db24615
Create Date: 2026-07-31 21:28:20.414488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ea6a95a1b7'
down_revision: Union[str, Sequence[str], None] = '7b452db24615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=True),
    sa.Column('default_currency', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_point_in_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_types_code'), 'metric_types', ['code'], unique=True)
    op.create_index(op.f('ix_metric_types_id'), 'metric_types', ['id'], unique=False)
    op.create_table('financing_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financing_rounds_id'), 'financing_rounds', ['id'], unique=False)
    op.create_table('metric_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('as_of_date', sa.DateTime(), nullable=True),
    sa.Column('observation_status', sa.String(), nullable=False),
    sa.Column('reporting_basis', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supersedes_observation_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ),
    sa.ForeignKeyConstraint(['supersedes_observation_id'], ['metric_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_observations_id'), 'metric_observations', ['id'], unique=False)
    op.create_table('financing_round_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financing_round_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['financing_round_id'], ['financing_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financing_round_facts_id'), 'financing_round_facts', ['id'], unique=False)
    op.create_table('observation_sources',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('source_excerpt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['metric_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id', 'source_id')
    )
    op.create_table('round_investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financing_round_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_numeric', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('amount_certainty', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['financing_round_id'], ['financing_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_investors_id'), 'round_investors', ['id'], unique=False)
    
    # DATA MIGRATION from investments to financing_rounds and round_investors
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id, investor_organization_id, company_organization_id, investment_date, round_type, total_round_amount, firm_investment_amount, is_lead, source_document_id, created_at, updated_at FROM investments"))
    investments = result.fetchall()
    
    rounds_map = {}
    for inv in investments:
        company_id = inv[2]
        round_type = inv[4] or "Unknown Round"
        investment_date = inv[3]
        created_at = inv[9] or sa.func.now()
        updated_at = inv[10] or sa.func.now()
        
        key = (company_id, round_type, investment_date)
        if key not in rounds_map:
            res = conn.execute(
                sa.text("INSERT INTO financing_rounds (company_id, round_name, status, created_at, updated_at) VALUES (:company_id, :round_name, 'closed', :created_at, :updated_at) RETURNING id"),
                {"company_id": company_id, "round_name": round_type, "created_at": created_at, "updated_at": updated_at}
            )
            round_id = res.fetchone()[0]
            rounds_map[key] = round_id
            
            if inv[5]:
                conn.execute(
                    sa.text("INSERT INTO financing_round_facts (financing_round_id, fact_type, value_text, value_date, certainty, reported_at, recorded_at, source_id) VALUES (:rid, 'amount_raised', :amt, :vdate, 'confirmed', :rdate, :rec, :sid)"),
                    {"rid": round_id, "amt": inv[5], "vdate": investment_date, "rdate": investment_date, "rec": created_at, "sid": inv[8]}
                )
                
        round_id = rounds_map[key]
        role = "lead" if inv[7] else "participant"
        conn.execute(
            sa.text("INSERT INTO round_investors (financing_round_id, investor_id, role, status, reported_at, recorded_at, source_id, notes) VALUES (:rid, :iid, :role, 'invested', :rdate, :rec, :sid, :notes)"),
            {"rid": round_id, "iid": inv[1], "role": role, "rdate": investment_date, "rec": created_at, "sid": inv[8], "notes": f"Firm Amount: {inv[6]}" if inv[6] else None}
        )
    
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.add_column('source_documents', sa.Column('source_tier', sa.Integer(), nullable=True))
    op.add_column('source_documents', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('source_documents', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'published_at')
    op.drop_column('source_documents', 'publisher')
    op.drop_column('source_documents', 'source_tier')
    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('investor_organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('investment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('round_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_lead', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_round_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firm_investment_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_organization_id'], ['organizations.id'], name=op.f('investments_company_organization_id_fkey')),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_profiles.id'], name=op.f('investments_fund_id_fkey')),
    sa.ForeignKeyConstraint(['investor_organization_id'], ['organizations.id'], name=op.f('investments_investor_organization_id_fkey')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('investments_source_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investments_pkey'))
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.drop_index(op.f('ix_round_investors_id'), table_name='round_investors')
    op.drop_table('round_investors')
    op.drop_table('observation_sources')
    op.drop_index(op.f('ix_financing_round_facts_id'), table_name='financing_round_facts')
    op.drop_table('financing_round_facts')
    op.drop_index(op.f('ix_metric_observations_id'), table_name='metric_observations')
    op.drop_table('metric_observations')
    op.drop_index(op.f('ix_financing_rounds_id'), table_name='financing_rounds')
    op.drop_table('financing_rounds')
    op.drop_index(op.f('ix_metric_types_id'), table_name='metric_types')
    op.drop_index(op.f('ix_metric_types_code'), table_name='metric_types')
    op.drop_table('metric_types')
    # ### end Alembic commands ###
