"""Add Sourcing Run Tables

Revision ID: 795d30f7ff2e
Revises: 8efb386b52a8
Create Date: 2026-05-09 14:33:10.880799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795d30f7ff2e'
down_revision: Union[str, Sequence[str], None] = '8efb386b52a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('ingestion_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(), nullable=False),
    sa.Column('ingestion_type', sa.String(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('http_method', sa.String(), nullable=True),
    sa.Column('query_params_json', sa.JSON(), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_configs_id'), 'ingestion_configs', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_config_id', sa.Integer(), nullable=False),
    sa.Column('job_status', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('job_logs_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_config_id'], ['ingestion_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('raw_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('matched_organization_id', sa.Integer(), nullable=True),
    sa.Column('matched_person_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_identifier', sa.String(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['matched_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['matched_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_entities_id'), 'raw_entities', ['id'], unique=False)
    op.create_index(op.f('ix_raw_entities_matched_organization_id'), 'raw_entities', ['matched_organization_id'], unique=False)
    op.create_index(op.f('ix_raw_entities_matched_person_id'), 'raw_entities', ['matched_person_id'], unique=False)
    op.create_index(op.f('ix_raw_entities_normalized_name'), 'raw_entities', ['normalized_name'], unique=False)
    op.create_table('entity_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('raw_entity_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('update_reason', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('update_action', sa.String(), nullable=True),
    sa.Column('update_status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['raw_entity_id'], ['raw_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_updates_id'), 'entity_updates', ['id'], unique=False)
    op.create_index(op.f('ix_entity_updates_organization_id'), 'entity_updates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entity_updates_person_id'), 'entity_updates', ['person_id'], unique=False)
    op.create_index(op.f('ix_entity_updates_raw_entity_id'), 'entity_updates', ['raw_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_updates_raw_entity_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_person_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_organization_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_id'), table_name='entity_updates')
    op.drop_table('entity_updates')
    op.drop_index(op.f('ix_raw_entities_normalized_name'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_matched_person_id'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_matched_organization_id'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_id'), table_name='raw_entities')
    op.drop_table('raw_entities')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_configs_id'), table_name='ingestion_configs')
    op.drop_table('ingestion_configs')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
