"""add_cost_tracking_to_pipelinerun

Revision ID: 7b452db24615
Revises: 280cc7b01445
Create Date: 2026-07-01 21:58:09.191094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b452db24615'
down_revision: Union[str, Sequence[str], None] = '280cc7b01445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('llm_total_tokens', sa.Integer(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('llm_estimated_cost_usd', sa.Float(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('exa_calls', sa.Integer(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('exa_estimated_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'exa_estimated_cost_usd')
    op.drop_column('pipeline_runs', 'exa_calls')
    op.drop_column('pipeline_runs', 'llm_estimated_cost_usd')
    op.drop_column('pipeline_runs', 'llm_total_tokens')
    # ### end Alembic commands ###
