"""rename pipeline_run to ingestion_run

Revision ID: 95672606ae2c
Revises: be849171c88c
Create Date: 2026-05-23 19:00:43.192791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95672606ae2c'
down_revision: Union[str, Sequence[str], None] = 'be849171c88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('run_status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.add_column('extraction_jobs', sa.Column('ingestion_run_id', sa.Integer(), nullable=False))
    op.drop_constraint('extraction_jobs_pipeline_run_id_fkey', 'extraction_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'extraction_jobs', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    op.drop_column('extraction_jobs', 'pipeline_run_id')
    op.add_column('source_documents', sa.Column('ingestion_run_id', sa.Integer(), nullable=False))
    op.drop_constraint('source_documents_pipeline_run_id_fkey', 'source_documents', type_='foreignkey')
    op.create_foreign_key(None, 'source_documents', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    op.drop_column('source_documents', 'pipeline_run_id')
    
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('pipeline_run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'source_documents', type_='foreignkey')
    op.create_foreign_key(op.f('source_documents_pipeline_run_id_fkey'), 'source_documents', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.drop_column('source_documents', 'ingestion_run_id')
    op.add_column('extraction_jobs', sa.Column('pipeline_run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'extraction_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('extraction_jobs_pipeline_run_id_fkey'), 'extraction_jobs', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.drop_column('extraction_jobs', 'ingestion_run_id')
    op.create_table('pipeline_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_created', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('pipeline_runs_pipeline_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_runs_pkey'))
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
