"""add document_class to SourceDocument

Revision ID: 99ed915f1667
Revises: 95672606ae2c
Create Date: 2026-05-23 21:44:12.036631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ed915f1667'
down_revision: Union[str, Sequence[str], None] = '95672606ae2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('document_class', sa.String(), nullable=True))
    op.add_column('source_documents', sa.Column('classification_result_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'classification_result_json')
    op.drop_column('source_documents', 'document_class')
    # ### end Alembic commands ###
