"""replace old ingestion framework with pipeline framework

Revision ID: 9e3a5c1ff1df
Revises: b6b8a9d7f92b
Create Date: 2026-05-10 18:27:24.730965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e3a5c1ff1df'
down_revision: Union[str, Sequence[str], None] = 'b6b8a9d7f92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('program_cohort_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_profiles.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['program_cohort_id'], ['program_cohorts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_table('extracted_data_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_data_raw_content_hash'), 'extracted_data_raw', ['content_hash'], unique=False)
    op.create_index(op.f('ix_extracted_data_raw_id'), 'extracted_data_raw', ['id'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('extracted_data_raw_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('extracted_payload_json', sa.JSON(), nullable=True),
    sa.Column('matched_organization_id', sa.Integer(), nullable=True),
    sa.Column('matched_person_id', sa.UUID(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_data_raw_id'], ['extracted_data_raw.id'], ),
    sa.ForeignKeyConstraint(['matched_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['matched_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_id'), 'extracted_entities', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_matched_organization_id'), 'extracted_entities', ['matched_organization_id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_matched_person_id'), 'extracted_entities', ['matched_person_id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_normalized_name'), 'extracted_entities', ['normalized_name'], unique=False)
    op.create_table('extracted_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('extracted_data_raw_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('source_extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('source_entity_type', sa.String(), nullable=True),
    sa.Column('source_entity_id', sa.String(), nullable=True),
    sa.Column('target_extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_type', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('relationship_payload_json', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_data_raw_id'], ['extracted_data_raw.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['source_extracted_entity_id'], ['extracted_entities.id'], ),
    sa.ForeignKeyConstraint(['target_extracted_entity_id'], ['extracted_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_relationships_id'), 'extracted_relationships', ['id'], unique=False)
    op.create_table('entity_audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('audit_action', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('extracted_entity_id', sa.Integer(), nullable=True),
    sa.Column('extracted_relationship_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_user_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_entity_id'], ['extracted_entities.id'], ),
    sa.ForeignKeyConstraint(['extracted_relationship_id'], ['extracted_relationships.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_audit_trail_entity_id'), 'entity_audit_trail', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_audit_trail_id'), 'entity_audit_trail', ['id'], unique=False)
    # Drop old tables in correct FK dependency order
    # entity_updates depends on raw_entities + ingestion_jobs
    op.drop_index(op.f('ix_entity_updates_raw_entity_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_person_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_organization_id'), table_name='entity_updates')
    op.drop_index(op.f('ix_entity_updates_id'), table_name='entity_updates')
    op.drop_table('entity_updates')
    # raw_entities depends on ingestion_jobs
    op.drop_index(op.f('ix_raw_entities_normalized_name'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_matched_person_id'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_matched_organization_id'), table_name='raw_entities')
    op.drop_index(op.f('ix_raw_entities_id'), table_name='raw_entities')
    op.drop_table('raw_entities')
    # ingestion_jobs depends on ingestion_configs
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ingestion_configs depends on data_sources
    op.drop_index(op.f('ix_ingestion_configs_id'), table_name='ingestion_configs')
    op.drop_table('ingestion_configs')
    # data_sources is standalone
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('auth_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('data_sources_pkey'))
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('entity_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingestion_job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('update_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], name=op.f('entity_updates_ingestion_job_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('entity_updates_organization_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('entity_updates_person_id_fkey')),
    sa.ForeignKeyConstraint(['raw_entity_id'], ['raw_entities.id'], name=op.f('entity_updates_raw_entity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_updates_pkey'))
    )
    op.create_index(op.f('ix_entity_updates_raw_entity_id'), 'entity_updates', ['raw_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_updates_person_id'), 'entity_updates', ['person_id'], unique=False)
    op.create_index(op.f('ix_entity_updates_organization_id'), 'entity_updates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entity_updates_id'), 'entity_updates', ['id'], unique=False)
    op.create_table('ingestion_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('config_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingestion_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endpoint_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('http_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('query_params_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('headers_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schedule_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_success_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('ingestion_configs_data_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_configs_pkey'))
    )
    op.create_index(op.f('ix_ingestion_configs_id'), 'ingestion_configs', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingestion_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_created', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_logs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingestion_config_id'], ['ingestion_configs.id'], name=op.f('ingestion_jobs_ingestion_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_jobs_pkey'))
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('raw_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingestion_job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched_organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matched_person_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('normalized_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_identifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_payload_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], name=op.f('raw_entities_ingestion_job_id_fkey')),
    sa.ForeignKeyConstraint(['matched_organization_id'], ['organizations.id'], name=op.f('raw_entities_matched_organization_id_fkey')),
    sa.ForeignKeyConstraint(['matched_person_id'], ['people.id'], name=op.f('raw_entities_matched_person_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_entities_pkey'))
    )
    op.create_index(op.f('ix_raw_entities_normalized_name'), 'raw_entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_raw_entities_matched_person_id'), 'raw_entities', ['matched_person_id'], unique=False)
    op.create_index(op.f('ix_raw_entities_matched_organization_id'), 'raw_entities', ['matched_organization_id'], unique=False)
    op.create_index(op.f('ix_raw_entities_id'), 'raw_entities', ['id'], unique=False)
    op.drop_index(op.f('ix_entity_audit_trail_id'), table_name='entity_audit_trail')
    op.drop_index(op.f('ix_entity_audit_trail_entity_id'), table_name='entity_audit_trail')
    op.drop_table('entity_audit_trail')
    op.drop_index(op.f('ix_extracted_relationships_id'), table_name='extracted_relationships')
    op.drop_table('extracted_relationships')
    op.drop_index(op.f('ix_extracted_entities_normalized_name'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_matched_person_id'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_matched_organization_id'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_extracted_data_raw_id'), table_name='extracted_data_raw')
    op.drop_index(op.f('ix_extracted_data_raw_content_hash'), table_name='extracted_data_raw')
    op.drop_table('extracted_data_raw')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
