"""add program_cohorts table and change program_memberships to use program_cohort_id

Revision ID: b6b8a9d7f92b
Revises: 3d89a706161c
Create Date: 2026-05-10 18:11:43.326005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b8a9d7f92b'
down_revision: Union[str, Sequence[str], None] = '3d89a706161c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_cohorts_id'), 'program_cohorts', ['id'], unique=False)
    op.add_column('program_memberships', sa.Column('program_cohort_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('program_memberships_program_id_fkey'), 'program_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'program_memberships', 'program_cohorts', ['program_cohort_id'], ['id'])
    op.drop_column('program_memberships', 'program_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_memberships', sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'program_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('program_memberships_program_id_fkey'), 'program_memberships', 'program_profiles', ['program_id'], ['id'])
    op.drop_column('program_memberships', 'program_cohort_id')
    op.drop_index(op.f('ix_program_cohorts_id'), table_name='program_cohorts')
    op.drop_table('program_cohorts')
    # ### end Alembic commands ###
