"""Add Investment table

Revision ID: be849171c88c
Revises: 4828553752d6
Create Date: 2026-05-23 11:09:30.320405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be849171c88c'
down_revision: Union[str, Sequence[str], None] = '4828553752d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_organization_id', sa.Integer(), nullable=False),
    sa.Column('company_organization_id', sa.Integer(), nullable=False),
    sa.Column('investment_date', sa.DateTime(), nullable=True),
    sa.Column('round_type', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['investor_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
