"""drop redundant threat and primary columns

Revision ID: c20fafe36454
Revises: b2daeff1c40a
Create Date: 2026-08-04 12:40:31.286044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20fafe36454'
down_revision: Union[str, Sequence[str], None] = 'b2daeff1c40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitive_analyses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('competitive_analysis_companies', 'threat_level_description')
    op.drop_column('competitive_analysis_companies', 'threat_level')
    op.drop_column('competitive_analysis_segments', 'threat_level_description')
    op.drop_column('competitive_analysis_segments', 'competitive_threat')
    op.drop_index(op.f('ix_company_market_segments_id'), table_name='market_segment_company_links')
    op.create_index(op.f('ix_market_segment_company_links_id'), 'market_segment_company_links', ['id'], unique=False)
    op.drop_column('market_segment_company_links', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_segment_company_links', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_market_segment_company_links_id'), table_name='market_segment_company_links')
    op.create_index(op.f('ix_company_market_segments_id'), 'market_segment_company_links', ['id'], unique=False)
    op.add_column('competitive_analysis_segments', sa.Column('competitive_threat', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('competitive_analysis_segments', sa.Column('threat_level_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('competitive_analysis_companies', sa.Column('threat_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('competitive_analysis_companies', sa.Column('threat_level_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('competitive_analyses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
