"""Add themes, user_notes, market_reputation, founded_year

Revision ID: c9c3c6da4c8c
Revises: ef731202f52c
Create Date: 2026-06-10 21:59:27.986169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c3c6da4c8c'
down_revision: Union[str, Sequence[str], None] = 'ef731202f52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('themes', sa.JSON(), nullable=True))
    op.add_column('fund_profiles', sa.Column('themes', sa.JSON(), nullable=True))
    op.add_column('fund_profiles', sa.Column('market_reputation', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('user_notes', sa.String(), nullable=True))
    op.add_column('investor_profiles', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('investor_profiles', sa.Column('themes', sa.JSON(), nullable=True))
    op.add_column('investor_profiles', sa.Column('user_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investor_profiles', 'user_notes')
    op.drop_column('investor_profiles', 'themes')
    op.drop_column('investor_profiles', 'founded_year')
    op.drop_column('fund_profiles', 'user_notes')
    op.drop_column('fund_profiles', 'market_reputation')
    op.drop_column('fund_profiles', 'themes')
    op.drop_column('company_profiles', 'themes')
    # ### end Alembic commands ###
