"""add_competitive_analysis

Revision ID: d4f3f38c4a0b
Revises: dcaa3260d5df
Create Date: 2026-08-03 09:28:23.913872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f3f38c4a0b'
down_revision: Union[str, Sequence[str], None] = 'dcaa3260d5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_market_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('competitive_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_company_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['subject_company_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_analyses_id'), 'competitive_analyses', ['id'], unique=False)
    op.create_table('market_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('segment_type', sa.String(), nullable=True),
    sa.Column('parent_segment_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['parent_segment_id'], ['market_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_segments_id'), 'market_segments', ['id'], unique=False)
    op.create_table('competitive_analysis_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitive_analysis_id', sa.Integer(), nullable=False),
    sa.Column('competitor_company_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('threat_level_description', sa.String(), nullable=True),
    sa.Column('competitive_notes', sa.String(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitive_analysis_id'], ['competitive_analyses.id'], ),
    sa.ForeignKeyConstraint(['competitor_company_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_analysis_companies_id'), 'competitive_analysis_companies', ['id'], unique=False)
    op.create_table('competitive_analysis_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitive_analysis_id', sa.Integer(), nullable=False),
    sa.Column('market_segment_id', sa.Integer(), nullable=False),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('threat_level_description', sa.String(), nullable=True),
    sa.Column('competitive_threat', sa.String(), nullable=True),
    sa.Column('analysis_notes', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitive_analysis_id'], ['competitive_analyses.id'], ),
    sa.ForeignKeyConstraint(['market_segment_id'], ['market_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_analysis_segments_id'), 'competitive_analysis_segments', ['id'], unique=False)
    op.create_table('company_market_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('market_segment_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('differentiation', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['market_segment_id'], ['market_segments.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_market_segments_id'), 'company_market_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_market_segments_id'), table_name='company_market_segments')
    op.drop_table('company_market_segments')
    op.drop_index(op.f('ix_competitive_analysis_segments_id'), table_name='competitive_analysis_segments')
    op.drop_table('competitive_analysis_segments')
    op.drop_index(op.f('ix_competitive_analysis_companies_id'), table_name='competitive_analysis_companies')
    op.drop_table('competitive_analysis_companies')
    op.drop_index(op.f('ix_market_segments_id'), table_name='market_segments')
    op.drop_table('market_segments')
    op.drop_index(op.f('ix_competitive_analyses_id'), table_name='competitive_analyses')
    op.drop_table('competitive_analyses')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
