"""Add comparison sets and transactions

Revision ID: d6b7d8e93e53
Revises: e71a99f182b2
Create Date: 2026-08-22 22:07:09.339390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b7d8e93e53'
down_revision: Union[str, Sequence[str], None] = 'e71a99f182b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_sets_id'), 'comparison_sets', ['id'], unique=False)
    op.create_table('comparison_set_company_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_set_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_set_company_links_id'), 'comparison_set_company_links', ['id'], unique=False)
    op.create_table('market_comparison_set_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('comparison_set_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_comparison_set_links_id'), 'market_comparison_set_links', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_name', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('announced_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('target_company_id', sa.Integer(), nullable=True),
    sa.Column('acquirer_company_id', sa.Integer(), nullable=True),
    sa.Column('transaction_value_numeric', sa.Float(), nullable=True),
    sa.Column('transaction_value_text', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acquirer_company_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_company_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.add_column('organizations', sa.Column('ownership_type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('exchange', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'exchange')
    op.drop_column('organizations', 'ticker')
    op.drop_column('organizations', 'ownership_type')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_market_comparison_set_links_id'), table_name='market_comparison_set_links')
    op.drop_table('market_comparison_set_links')
    op.drop_index(op.f('ix_comparison_set_company_links_id'), table_name='comparison_set_company_links')
    op.drop_table('comparison_set_company_links')
    op.drop_index(op.f('ix_comparison_sets_id'), table_name='comparison_sets')
    op.drop_table('comparison_sets')
    # ### end Alembic commands ###
