"""Add llm_model_used to SourceDocument

Revision ID: dcaa3260d5df
Revises: 64ea6a95a1b7
Create Date: 2026-08-02 20:48:39.917109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcaa3260d5df'
down_revision: Union[str, Sequence[str], None] = '64ea6a95a1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('llm_model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'llm_model_used')
    # ### end Alembic commands ###
