"""Add accession_number to FundProfile

Revision ID: ef731202f52c
Revises: 063b594c7675
Create Date: 2026-05-30 10:46:52.301420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef731202f52c'
down_revision: Union[str, Sequence[str], None] = '063b594c7675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_profiles', sa.Column('accession_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_profiles', 'accession_number')
    # ### end Alembic commands ###
