"""Split fund_size and add fund_id to investment

Revision ID: f366c4d9af01
Revises: 99ed915f1667
Create Date: 2026-05-28 22:02:14.687403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f366c4d9af01'
down_revision: Union[str, Sequence[str], None] = '99ed915f1667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_profiles', sa.Column('fund_size_raised', sa.String(), nullable=True))
    op.add_column('fund_profiles', sa.Column('fund_size_target', sa.String(), nullable=True))
    op.drop_column('fund_profiles', 'fund_size')
    op.add_column('investments', sa.Column('fund_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'investments', 'fund_profiles', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_column('investments', 'fund_id')
    op.add_column('fund_profiles', sa.Column('fund_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fund_profiles', 'fund_size_target')
    op.drop_column('fund_profiles', 'fund_size_raised')
    # ### end Alembic commands ###
