"""Add ProgramMembership table

Revision ID: f42e72a66eaf
Revises: 795d30f7ff2e
Create Date: 2026-05-09 21:11:17.966127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42e72a66eaf'
down_revision: Union[str, Sequence[str], None] = '795d30f7ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_organization_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_memberships_id'), 'program_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_memberships_id'), table_name='program_memberships')
    op.drop_table('program_memberships')
    # ### end Alembic commands ###
